apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dashboard"
  namespace: "default"
  labels:
    app: "dashboard"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "dashboard"
  template:
    metadata:
      labels:
        app: "dashboard"
    spec:
      containers:
      - name: "dashboard_container"
        image: dashboard:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 512Mi
            cpu: "0.05"
          limits:
            memory: 2048Mi
            cpu: "2.0"           
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "dashboard-service"
  namespace: "default"
  labels:
    app: "dashboard"
spec:
  type: "LoadBalancer"
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "dashboard"
  type: "NodePort"
