apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dashboard"
  namespace: "default"
  labels:
    app: "dashboard"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "dashboard"
  template:
    metadata:
      labels:
        app: "dashboard"
    spec:
      containers:
      - name: "dashboard-container"
        image: gcr.io/wide-pulsar-254811/dash_2:latest
        imagePullPolicy: Always
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "dashboard-service"
  namespace: "default"
  labels:
    app: "dashboard"
spec:
  type: "LoadBalancer"
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "dashboard"
